### ISSUE TITLE
Document &dash;

### ISSUE THREAD

**Issue by MartinPacker** [MartinPacker/md2pptx#113]
This symbol seems to have been added in the code - but not added to the symbol table in the documentation.

**Comment by MartinPacker** [comment]
Done - post v2.6.1.

**Comment by chipset** [comment]
Sorry about that.  I forgot to mention it.  I added it due to some bad translation on one of my PPTs.  

Sent from my iPad

> On Mar 20, 2022, at 4:51 AM, Martin Packer ***@***.***> wrote:
> 
> ﻿
> Closed #113.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you are subscribed to this thread.

-- 
This electronic communication and the information and any files transmitted 
with it, or attached to it, are confidential and are intended solely for 
the use of the individual or entity to whom it is addressed and may contain 
information that is confidential, legally privileged, protected by privacy 
laws, or otherwise restricted from disclosure to anyone else. If you are 
not the intended recipient or the person responsible for delivering the 
e-mail to the intended recipient, you are hereby notified that any use, 
copying, distributing, dissemination, forwarding, printing, or copying of 
this e-mail is strictly prohibited. If you received this e-mail in error, 
please return the e-mail to the sender, delete it from your computer, and 
destroy any printed copy of it.

**Comment by MartinPacker** [comment]
Not a problem. Did you in fact also want em dash and en dash as symbols?

BTW you could also use the numeric value - though this way is friendlier.

**Comment by chipset** [comment]
I did intend that.  I was running into issues doing the conversion.  That was my first mod a couple months ago.  I believe it has to do with the conversion routine.  I used pptx2md to create some PowerPoints and it was converting MS/PPTs “dash dash” into a long dash as part of the auto formatting.  Not good for Zowe’s command line options.  

Sent from my iPad

> On Mar 20, 2022, at 9:45 AM, Martin Packer ***@***.***> wrote:
> 
> ﻿
> Not a problem. Did you in fact also want em dash and en dash as symbols?
> 
> BTW you could also use the numeric value - though this way is friendlier.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you commented.

-- 
This electronic communication and the information and any files transmitted 
with it, or attached to it, are confidential and are intended solely for 
the use of the individual or entity to whom it is addressed and may contain 
information that is confidential, legally privileged, protected by privacy 
laws, or otherwise restricted from disclosure to anyone else. If you are 
not the intended recipient or the person responsible for delivering the 
e-mail to the intended recipient, you are hereby notified that any use, 
copying, distributing, dissemination, forwarding, printing, or copying of 
this e-mail is strictly prohibited. If you received this e-mail in error, 
please return the e-mail to the sender, delete it from your computer, and 
destroy any printed copy of it.

**Comment by MartinPacker** [comment]
Sounds like - from your use case - em-dash and en-dash aren't immediate priorities.

Anyway we can discuss stuff you need in Dallas. Won't be long now. :-)

**Comment by chipset** [comment]
No, it won’t.  I’ll be at Share Monday morning.  

Sent from my iPad

> On Mar 20, 2022, at 9:54 AM, Martin Packer ***@***.***> wrote:
> 
> ﻿
> Sounds like - from your use case - em-dash and en-dash aren't immediate priorities.
> 
> Anyway we can discuss stuff you need in Dallas. Won't be long now. :-)
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you commented.

-- 
This electronic communication and the information and any files transmitted 
with it, or attached to it, are confidential and are intended solely for 
the use of the individual or entity to whom it is addressed and may contain 
information that is confidential, legally privileged, protected by privacy 
laws, or otherwise restricted from disclosure to anyone else. If you are 
not the intended recipient or the person responsible for delivering the 
e-mail to the intended recipient, you are hereby notified that any use, 
copying, distributing, dissemination, forwarding, printing, or copying of 
this e-mail is strictly prohibited. If you received this e-mail in error, 
please return the e-mail to the sender, delete it from your computer, and 
destroy any printed copy of it.
