### ISSUE TITLE
Support And Require Python 3

### ISSUE THREAD

**Issue by 42sol-eu** [MartinPacker/md2pptx#2]
Is this script available in python 3?

**Comment by MartinPacker** [comment]
Hi! (You can use multiple identifiers but you’re still the same you.) :-)

The truthful answer is “I really don’t know”.

It’s not too late to prerequisite Python 3 - and I’d like to do that. (I don’t see why we should support Python 2 at the same time.)

I’ll admit my current sensitivity to 3 versus 2 is in the form of `print()`.

Please check and report breakage - on 3.

(filterCSV, by the way, **is** Python 3 only.)

I have a couple of bugs  I need to resolve urgently in md2pptx so I’d suggest you report breakage rather than fixing it yourself. (Hopefully it will be feasible to contribute directly very soon. Note: I’m not a git expert yet.)

**Comment by 42sol-eu** [comment]
To be clear. I only use and want python 3.

I was misled by the documentation  under "How Do You Use md2pptx?"


> Have Python 2 installed - at a reasonably high level.

This should be Python **3** if I read your reply.

**Comment by MartinPacker** [comment]
I only want Python 3, too. This issue will be resolved when we can update the documentation to say "Have Python 3 installed..."

It needs testing and possible bugfixing before we can make that statement.

(And I'm not aware of any users who want Python 2 so we can decide this is our position.)

**Comment by MartinPacker** [comment]
So, I had quite a lot of repair work to do to make it work with Python 3. I think there will be more. Mostly in the area of things being floats when python-pptx wants integers.

What I'll upload today will need further testing.

I wouldn't suggest modifying it - but rather reporting breakage.

This upload also fixes Issue 3 - which I'm about to close.

**Comment by MartinPacker** [comment]
Looks like it works fine with Python 3. Will fix any breakage as separate issues.
